@local=http://localhost:3005

### register 
 POST {{local}}/users
 Content-Type: application/json

 {
    "name": "iam_adminshlomi",
    "email": "admin.me@adminsh.com",
    "biz": true,
    "admin":true,
    "password": "unme555"
 }

### log in
POST  {{local}}/users/login
Content-Type: application/json

{
    "email": "admin.me@adminsh.com",
    "password": "unme555"
}

### Admin - get all users
GET {{local}}/users
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg2M2U0YzZlY2Y3ZWZlYTMwMDA3NzkiLCJiaXoiOnRydWUsImFkbWluIjp0cnVlLCJpYXQiOjE3MzY4NTU2Mjd9.7D7sGYx1uqlbkfcMCJS1wanCfzTE4FlqXrUR1EVia_s

### get user by id
GET {{local}}/users/675b2738a6c8f8f017fcc08f
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg2M2U0YzZlY2Y3ZWZlYTMwMDA3NzkiLCJiaXoiOnRydWUsImFkbWluIjp0cnVlLCJpYXQiOjE3MzY4NTU2Mjd9.7D7sGYx1uqlbkfcMCJS1wanCfzTE4FlqXrUR1EVia_s

{
}

### update user
PUT {{local}}/users/675b2738a6c8f8f017fcc08f
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg2M2U0YzZlY2Y3ZWZlYTMwMDA3NzkiLCJiaXoiOnRydWUsImFkbWluIjp0cnVlLCJpYXQiOjE3MzY4NTU2Mjd9.7D7sGYx1uqlbkfcMCJS1wanCfzTE4FlqXrUR1EVia_s
Content-Type: application/javascript

{
  "name":"bobi bob"  
}

### auth
POST   {{local}}/api/auth
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzYwNTJjNWM5ODNiYzI3MTViZTBjNTEiLCJiaXoiOnRydWUsImlhdCI6MTczNDYxNDIwMn0.cK1hGHn5AAWPGqIacD9myoS8sUMQLTuo_cIPoQWh9VM
Content-Type: application/json

{
    "email": "aslljhl@pop.com",
    "password": "unme555"
}

###
POST {{local}}/api/cards
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzYwNTJjNWM5ODNiYzI3MTViZTBjNTEiLCJiaXoiOnRydWUsImlhdCI6MTczNDYxNDIwMn0.cK1hGHn5AAWPGqIacD9myoS8sUMQLTuo_cIPoQWh9VM

 {"bizName": "lolllo",
    "bizDescription":"kkk ggg ddd sss" ,
    "bizAddress": "jj hhgg gyyyyyy gghg",
    "bizPhone": "050444777"
 }